import fs from 'node:fs'
import path from 'node:path'
import { spawnSync } from 'node:child_process'

const root = process.cwd()
const tscBin = path.join(root, 'node_modules', 'typescript', 'bin', 'tsc')
const read = file => fs.readFileSync(path.join(root, file), 'utf8')
const exists = file => fs.existsSync(path.join(root, file))
const checks = []
const add = (group, name, pass, evidence) => checks.push({ group, name, pass: Boolean(pass), evidence })
const source = {
  types: read('src/types.ts'), app: read('src/App.tsx'), context: read('src/AppContext.tsx'), planner: read('src/lib/planner.ts'),
  seed: read('src/lib/seed.ts'), state: read('src/lib/state.ts'), db: read('src/lib/db.ts'), supabase: read('src/lib/supabase.ts'),
  goals: read('src/lib/goals.ts'), styles: read('src/styles.css'), stats: read('src/components/StatsPage.tsx'),
  proposal: read('src/components/ProposalDialog.tsx'), review: read('src/components/ReviewDialog.tsx'), constraints: read('src/components/CalendarConstraintManager.tsx'), adjustment: read('src/components/AdjustmentIntentDialog.tsx'), adjustmentPolicy: read('src/lib/adjustment.ts'), taskCard: read('src/components/TaskCard.tsx'),
  single: read('src/components/SingleTaskDialog.tsx'), group: read('src/components/TaskGroupDialog.tsx'), addTask: read('src/components/AddTaskDialog.tsx'), versions: read('src/lib/versions.ts'), conflicts: read('src/lib/conflicts.ts'),
}
const pkg = JSON.parse(read('package.json'))
const releaseVersion = `v${pkg.version}`
add('版本与迁移', '发布版本为 0.9.0', pkg.version === '0.9.0', `package.json: ${pkg.version}`)
add('版本与迁移', '状态架构版本已提升（当前为 11）', /SCHEMA_VERSION\s*=\s*11/.test(source.types), 'src/types.ts；执行账本与历史状态事件使用独立版本迁移')
add('版本与迁移', '存在确定性 v0.7→v0.8 迁移', /migrat|迁移/.test(source.seed) && /coreTargetDate/.test(source.seed) && /calendarConstraints/.test(source.seed), 'src/lib/seed.ts')
add('版本与迁移', '旧全局目标日期不再出现在当前界面与当前调度计算', !/settings\.coreTargetDate|settings\.chemistryTargetDate/.test(source.app + source.stats + source.planner), '仅 seed/types 保留迁移兼容字段')
add('领域模型', 'Goal 与三种完成条件', /interface Goal\b/.test(source.types) && /'all'\s*\|\s*'percentage'\s*\|\s*'count'/.test(source.types), 'src/types.ts')
add('领域模型', '多目标关联与直接任务关联', /linkedTaskGroupIds/.test(source.types) && /linkedAssignmentIds/.test(source.types), 'src/types.ts')
add('领域模型', '没有独立 Milestone 实体', !/interface\s+Milestone|type\s+Milestone|class\s+Milestone/.test(Object.values(source).join('\n')), 'src 全量扫描')
add('领域模型', '统一 CalendarConstraint 支持范围', /interface CalendarConstraint/.test(source.types) && /startDate/.test(source.constraints) && /endDate/.test(source.constraints), 'types + CalendarConstraintManager')
add('领域模型', '变化事件、方案、计划版本齐全', /interface PlanChangeEvent/.test(source.types) && /interface SchedulingProposal/.test(source.types) && /interface PlanVersion/.test(source.types), 'src/types.ts')
add('创建系统', '统一添加任务入口支持独立任务与任务组', /TaskCreationMode/.test(source.addTask) && /TaskCreationKind/.test(source.addTask) && /添加到录入，暂不安排/.test(source.addTask) && /添加任务并安排/.test(source.addTask) && /选择任务类型/.test(source.addTask) && exists('src/components/SingleTaskDialog.tsx') && exists('src/components/TaskGroupDialog.tsx'), 'AddTaskDialog + task dialogs')
add('创建系统', '单项任务支持归组、独立、系统/偏好/锁定日期', /standalone/.test(source.single) && /system/.test(source.single) && /prefer-date/.test(source.single) && /lock-date/.test(source.single), 'SingleTaskDialog')
add('创建系统', '任务创建先准备再预览', /prepareSingleAssignment/.test(source.context) && /prepareTaskGroup/.test(source.context) && /openPrepared/.test(source.app), 'AppContext + App')
add('创建系统', '任务组增减保护已完成/有记录/锁定/计时任务', /prepareTaskGroupEdit/.test(source.context) && /protectedIds/.test(source.context) && /actualMinutes === 0/.test(source.context), 'AppContext')
add('目标系统', '目标为顶级导航页', /id: 'goals'/.test(source.app) && /<GoalsPage/.test(source.app), 'App.tsx')
add('目标系统', '最近相关期限，不按目标数量加权', /nearestRelevantGoalDate/.test(source.goals) && /relevantGoalPriority/.test(source.goals) && /conditionCountedAssignmentIds/.test(source.goals), 'src/lib/goals.ts')
add('目标系统', '多目标统计去重', /counted = new Set/.test(source.goals) && /globalAssignmentIds|new Set/.test(source.stats), 'goals + stats')
add('目标系统', '目标和任务组自动完成生命周期', /updateGoalAndGroupLifecycle/.test(source.goals) && /status: 'completed'/.test(source.goals), 'src/lib/goals.ts')
add('调度核心', 'Insert/Repair/Optimize/Rebuild 共用一个入口', /SchedulingAction/.test(source.types) && /generateSchedulingProposals/.test(source.planner) && /event\.action/.test(source.planner), 'types + planner')
add('调度核心', '过去/今日、计时、锁定、手动意图、容量与上限仍受校验', /active timer|timer\.assignmentId|intentStrength|dailyMax|high-intensity|long/.test(source.planner), 'src/lib/planner.ts')
add('调度核心', '目标最晚日期作为硬约束', /nearestRelevantLatestDate/.test(source.planner) && /hard/.test(source.planner), 'src/lib/planner.ts')
add('调度核心', '无合法位置时不强塞', /不会强塞|没有合法|未强行安排/.test(source.planner + source.proposal), 'planner + proposal UI')
add('调度核心', '方案计算可取消且不阻塞主线程', exists('src/workers/proposal.worker.ts') && /terminate\(\)/.test(source.app) && /取消计算/.test(source.app), 'Web Worker + cancel')
add('调度核心', '时长证据只建议放宽上限，不自动修改', /系统只提出建议，不会自动提高上限/.test(source.planner), 'src/lib/planner.ts')
add('可解释方案', '所有摘要计数可展开到具体项目', /<details/.test(source.proposal) && /任务变化/.test(source.proposal) && /问题明细/.test(source.proposal), 'ProposalDialog')
add('可解释方案', '任务、日期、负载、目标均有前后对比', /before-after/.test(source.proposal) && /日期负载(?:与任务)?前后/.test(source.proposal) && /目标影响/.test(source.proposal), 'ProposalDialog')
add('可解释方案', '解释为什么不选其他日期', /为什么没有安排到其他日期/.test(source.proposal) && /rejectedAlternatives/.test(source.planner), 'proposal + planner')
add('可解释方案', '更多替代方案按结果签名去重', /distinctSignature/.test(source.planner) && /signatures\.has/.test(source.planner) && /(?:真正|实质)不同/.test(source.proposal), 'planner + UI')
add('可解释方案', '默认只计算推荐方案，其他方案按需生成', /const initialPreferences = \[policy\.primaryPreference\]/.test(source.app) && /initialVisibleCount/.test(source.proposal) && /生成更多不同方案/.test(source.proposal), 'App orchestration + ProposalDialog')
add('可解释方案', '系统将执行的全部变化都经过预览', /previewPreparedChange/.test(source.app) && /计划调整预览/.test(source.proposal) && /应用预览中的改动/.test(source.proposal), 'App + ProposalDialog')
add('可解释方案', '负载增减使用红绿方向提示', /load-delta-up/.test(source.proposal) && /load-delta-down/.test(source.proposal) && /\.load-delta-up/.test(source.styles) && /\.load-delta-down/.test(source.styles), 'ProposalDialog + styles')
add('事件编排', '复盘已选日期只校验不二次重排', /requestedCarryDates/.test(source.context) && /validate-and-commit/.test(source.adjustmentPolicy) && !/比较完整调整方案/.test(source.review), 'Review + policy')
add('事件编排', '复盘完成页提供直接执行、更多方案和仅保存三条路径', /完成复盘，并按当前方案顺延/.test(source.review) && /获取更多方案/.test(source.review) && /仅保存复盘，暂不顺延/.test(source.review) && /forceAlternatives/.test(source.app), 'Review + App orchestration')
add('调度核心', '已完成历史不会单独生成待处理硬冲突', /已经完成\/已经发生的用时与任务数量只作为历史基线/.test(source.planner) && /ordinaryUnfinished\.length > 0 && day\.plannedMinutes > 0/.test(source.planner) && /worsenedHardConstraintFacts/.test(source.planner), 'planner historical/adjustable split')
add('事件编排', '合法精确选择在冲突修复中保持固定', /fixedAssignmentIds/.test(source.app) && /fixedAssignmentIds\(request\)/.test(source.planner), 'App + planner')
add('事件编排', '明确局部操作第一方案只执行用户操作', /explicitLocalOperation/.test(source.context) && /operationScope:\s*'requested-change-only'/.test(source.context) && /明确的局部操作永远先展示/.test(source.app) && /只执行本次调整/.test(source.proposal), 'AppContext + policy + ProposalDialog')
add('事件编排', '既有问题不扩大本次操作范围', /ProposalIssueDelta/.test(source.types) && /hardConstraintIssueDelta/.test(source.planner) && /计划原有/.test(source.proposal) && /新增或恶化/.test(source.proposal), 'planner delta + UI')
add('事件编排', '删除任务与任务组先走最小作用域预览', /prepareAssignmentDelete/.test(source.context) && /prepareTaskGroupDelete/.test(source.context) && /prepareAssignmentDelete\(taskOpen\.id\)/.test(source.app) && /prepareTaskGroupDelete\(group\.id\)/.test(source.app), 'AppContext + App')
add('事件编排', '目标放宽和容量增加默认为保持现状', /optional-optimization/.test(source.adjustmentPolicy) && /保存目标变化并保持当前排期/.test(source.adjustmentPolicy) && /保存新的可用时间并保持当前排期/.test(source.adjustmentPolicy), 'adjustment policy')
add('复盘与时长', '复盘默认摘要优先，图表按需展开', /review-hero/.test(source.review) && /review-summary-grid/.test(source.review) && /chartsOpen/.test(source.review) && /展开图表/.test(source.review), 'ReviewDialog')
add('复盘与时长', '最近 10 个有效样本与 IQR 异常值处理', /windowSize/.test(source.planner) && /slice\(0, state\.settings\.duration\.windowSize\)/.test(source.planner) && /1\.5 \* iqr/.test(source.planner), 'src/lib/planner.ts')
add('复盘与时长', '时长建议先预览且不静默重排', /prepareDurationChange/.test(source.context) && /预览更新影响/.test(source.review) && /更新预计时长并保持日期/.test(source.adjustmentPolicy) && /只应用新预计，日期保持不变/.test(source.app), 'Review + adjustment policy + App')
add('复盘与时长', '复盘包含任务/任务组/日趋势/完成率/误差/组均值图表', /今日各任务/.test(source.review) && /今日各任务组/.test(source.review) && /预计误差趋势/.test(source.review) && /任务组默认预计/.test(source.review), 'ReviewDialog')
add('复盘与时长', '不评价正确率、掌握或学习质量', /不评价正确率、掌握程度或学习质量/.test(source.review), 'ReviewDialog')
add('版本与统计', '重大变化创建本地计划版本', /createPlanVersion/.test(source.context) && /createVersionFromProposal/.test(source.context), 'AppContext')
add('版本与统计', '恢复前保存当前状态并保留执行记录', /恢复前/.test(source.versions) || /current|当前/.test(source.versions), 'src/lib/versions.ts')
add('版本与统计', '云端可移植状态排除大版本历史', /planVersions:\s*\[\]/.test(source.state) && /portable/.test(source.supabase), 'state + supabase')
add('账号与数据', '游客修改注册时提供导入/分离选择', /guestImportAvailable/.test(source.app) && /导入已修改的游客计划/.test(source.app) && /游客数据仍独立保留/.test(source.app), 'App.tsx')
add('账号与数据', '游客、账号命名空间隔离', /namespace/.test(source.context) && /setDataSpace/.test(source.context), 'AppContext')
add('移动端/PWA', 'Today 浮动按钮与快捷面板已移除', !/mobile-quick-fab|mobile-quick-actions/.test(source.app + source.styles), 'App + styles')
add('移动端/PWA', '安全区、100dvh、无横向溢出规则', /safe-area-inset-bottom/.test(source.styles) && /100dvh/.test(source.styles) && /overflow-x:hidden/.test(source.styles), 'styles.css')
add('移动端/PWA', '月历移动端保留七列', /repeat\(7/.test(source.styles), 'styles.css')
add('移动端/PWA', '复杂预览采用 100dvh 弹性全屏且正文独立滚动', /modal-mobile-fullscreen/.test(source.styles) && /height:100dvh/.test(source.styles) && /\.modal-body\{[^}]*overflow-y:auto/.test(source.styles), 'styles.css')
add('移动端/PWA', '选择状态具有明显视觉反馈', /choice-indicator/.test(source.adjustment) && /aria-pressed/.test(source.adjustment) && /\.adjustment-preference-options button\.selected/.test(source.styles) && /\.proposal-choice\.selected/.test(source.styles), 'dialogs + styles')
add('移动端/PWA', 'Today 头部手机端按内容高度布局', /today-hero-main/.test(source.app) && /\.today-hero\{display:grid!important/.test(source.styles) && /height:auto!important;min-height:0!important/.test(source.styles) && /flex:none!important/.test(source.styles), 'App + styles')
add('冲突决策', '硬冲突可逐项查看并选择处理方式', /ConflictDecisionPanel/.test(source.proposal) && /conflictProfile/.test(source.conflicts) && /allowedResolutions/.test(source.types), 'ProposalDialog + conflicts')
add('冲突决策', '换日、修改条件和撤销调整按用途分层', /处理当前任务/.test(source.proposal) && /修改产生冲突的条件/.test(source.proposal) && /不继续这部分调整/.test(source.proposal), 'ProposalDialog')
add('冲突决策', '部分接受例外后带条件重新计算', /applyConflictDecisions/.test(source.app) && /exceptionDecisions/.test(source.conflicts) && /disableAutomaticExceptions:\s*true/.test(source.app), 'App + conflicts + planner')
add('冲突决策', '一次性例外精确到日期规则和任务', /affectedAssignmentIds/.test(source.types) && /mergeConstraintExceptions/.test(source.conflicts) && /候选任务不在授权范围内时/.test(source.planner), 'types + conflicts + planner')
add('冲突决策', '冲突状态不再简单禁用应用按钮', /按这些选择重新计算/.test(source.proposal) && /处理 \$\{unresolvedCount\} 个待决定问题/.test(source.proposal) && !/disabled=\{selected\?\.infeasible/.test(source.proposal), 'ProposalDialog')
add('冲突决策', '无候选仍有可点击的解决入口', /proposal-no-solution/.test(source.proposal) && /扩大范围继续寻找/.test(source.proposal) && /调整可用时间/.test(source.proposal) && /调整目标/.test(source.proposal), 'ProposalDialog')
add('移动端/PWA', 'PWA standalone 配置', /display:\s*'standalone'/.test(read('vite.config.ts')), 'vite.config.ts')
add('未来边界', 'AI 仅保留解析接口，没有实现功能', exists('src/lib/intent.ts') && /interface PlanIntentParser/.test(read('src/lib/intent.ts')) && !/fetch\(|openai|deepseek/i.test(read('src/lib/intent.ts')), 'src/lib/intent.ts')


add('典型场景', '目标事件日期不再误作调度起点', /function proposalPlanningStart/.test(source.planner) && /state\.settings\.startDate/.test(source.planner) && /const today = todayISO\(\)/.test(source.planner), 'goal/trip/new task can use current future window')
add('典型场景', '部分目标只约束满足条件所需任务', /conditionCountedAssignmentIds/.test(source.goals) && /goalAppliesToAssignment/.test(source.goals), '50% teacher check does not pull the other 50% forward')
add('典型场景', '目标变更事件只纳入条件实际计数任务', /goalProgress\(before, existing\)/.test(source.context) && /goalProgress\(next, goal\)/.test(source.context) && /affectedAssignmentIds/.test(source.context), 'partial Goal edits do not nominate the whole linked group for movement')
add('典型场景', '计划太累转化为具体减负结果', /load-preference-change/.test(source.adjustment) && /每天最多安排（分钟）/.test(source.adjustment) && /最多连续几个高负载日/.test(source.adjustment) && /exploratory-optimization/.test(source.adjustmentPolicy), 'AdjustmentIntentDialog + orchestration policy')
add('交互融合', '结束今天与复盘已合并为单一入口', (source.app.match(/结束今天并复盘/g) ?? []).length === 1 && /completeReview/.test(source.context) && /处理未完成任务/.test(source.review), 'Today + ReviewDialog')
add('交互融合', '完成任务更多按钮使用固定横向图形', /Ellipsis/.test(source.taskCard) && !/more-dots[^>]*>···/.test(source.taskCard), 'TaskCard')
add('交互融合', '桌面日期与操作不再被单字拆行', /date-switcher h2\{white-space:nowrap/.test(source.styles) && /today-hero-actions button\{white-space:nowrap/.test(source.styles), 'styles.css')
add('交互融合', '复盘具有视觉摘要、任务决策卡与按需图表', /review-progress-ring/.test(source.review) && /review-task-decision/.test(source.review) && /review-charts/.test(source.review), 'ReviewDialog + styles')

const tsc = spawnSync(process.execPath, [tscBin, '-p', 'tsconfig.check.json', '--pretty', 'false'], { cwd: root, encoding: 'utf8' })
add('自动验证', '严格 TypeScript 静态检查', tsc.status === 0, (tsc.stdout + tsc.stderr).trim() || '通过')
const scale = spawnSync(process.execPath, ['scripts/performance-v08.mjs'], { cwd: root, encoding: 'utf8' })
add('自动验证', '20目标/50组/500任务/30约束/10版本规模验证', scale.status === 0, scale.status === 0 ? '通过，详见 validation/500任务规模验证.json' : (scale.stdout + scale.stderr).trim())
const adjustmentRuntime = spawnSync(process.execPath, ['scripts/runtime-adjustment-v0810.mjs'], { cwd: root, encoding: 'utf8' })
add('自动验证', '复盘、历史冲突与局部操作作用域运行验证', adjustmentRuntime.status === 0, adjustmentRuntime.status === 0 ? '通过；既有冲突不阻止局部删除，且其他任务移动为 0' : (adjustmentRuntime.stdout + adjustmentRuntime.stderr).trim())
const intakeRuntime = spawnSync(process.execPath, ['scripts/runtime-intake-v09.mjs'], { cwd: root, encoding: 'utf8' })
add('自动验证', '录入工作区不触发排期且千项写入保持流畅', intakeRuntime.status === 0, intakeRuntime.status === 0 ? '通过；正式计划零改动，详见 validation/录入工作区运行时验证.json' : (intakeRuntime.stdout + intakeRuntime.stderr).trim())
const plannerPerformance = spawnSync(process.execPath, ['scripts/runtime-planner-performance.mjs'], { cwd: root, encoding: 'utf8', timeout: 300000 })
add('自动验证', '100/500/1000 项真实调度与增量场景性能基准', plannerPerformance.status === 0, plannerPerformance.status === 0 ? '通过；记录 P50/P95、基准设备与既有任务移动范围，详见 validation/真实调度性能基准.json' : (plannerPerformance.stdout + plannerPerformance.stderr).trim())
const scenarios = spawnSync(process.execPath, ['scripts/scenario-v0810.mjs'], { cwd: root, encoding: 'utf8' })
add('自动验证', '核心场景与三大系统架构验证', scenarios.status === 0, scenarios.status === 0 ? `全部通过，详见 validation/${releaseVersion}场景架构验证.md` : (scenarios.stdout + scenarios.stderr).trim())
const uiAudit = spawnSync(process.execPath, ['scripts/ui-audit-v0810.mjs'], { cwd: root, encoding: 'utf8' })
add('自动验证', '桌面与手机界面布局审计', uiAudit.status === 0, uiAudit.status === 0 ? `全部通过，详见 validation/${releaseVersion}界面布局审计.md` : (uiAudit.stdout + uiAudit.stderr).trim())
const efficiency = spawnSync(process.execPath, ['scripts/user-efficiency-v0810.mjs'], { cwd: root, encoding: 'utf8' })
add('自动验证', '全流程用户效率与统计口径验证', efficiency.status === 0, efficiency.status === 0 ? `全部通过，详见 validation/${releaseVersion}用户效率验证.md` : (efficiency.stdout + efficiency.stderr).trim())

const passed = checks.filter(item => item.pass).length
const result = { version: pkg.version, generatedAt: new Date().toISOString(), passed, total: checks.length, failed: checks.filter(item => !item.pass), checks }
fs.mkdirSync(path.join(root, 'validation'), { recursive: true })
fs.writeFileSync(path.join(root, 'validation', `${releaseVersion}自动验证结果.json`), JSON.stringify(result, null, 2))
const lines = [`# ${releaseVersion} 自动验证结果`, '', `- 通过：${passed} / ${checks.length}`, `- 生成时间：${result.generatedAt}`, '', ...checks.map(item => `- ${item.pass ? '✅' : '❌'} **${item.group}｜${item.name}**：${item.evidence}`)]
fs.writeFileSync(path.join(root, 'validation', `${releaseVersion}自动验证结果.md`), lines.join('\n') + '\n')
console.log(lines.join('\n'))
if (passed !== checks.length) process.exit(1)
